COM-1080 add max retries parameter to readme
keboola/db-extractor-mysql pull request #161
Opened 2022-01-17 12:32 UTC by AdamVyborny

https://keboola.atlassian.net/browse/COM-1080

2022-01-17 12:37 UTC, ondrajodas requested changes
automaticky se to sem nepropíše, budeš muset aktualizovat knihovnu, která ještě není hotová :)

a nejjlíp kdyby tu byl nějaký jednoduchý test

2022-01-17 13:00 UTC, AdamVyborny commented
> automaticky se to sem nepropíše, budeš muset aktualizovat knihovnu, která ještě není hotová :)
> 
> a nejjlíp kdyby tu byl nějaký jednoduchý test

Jo, sorry. Tohle měl bejt zatím draft, pak přidám do composeru novou verzi. A případně nějaký ten test :)

2022-01-18 10:17 UTC, AdamVyborny commented
> ještě by to chtělo nějaký funkcionální test aby bylo vidět že to opravdu funguje

Teoreticky stačí přidat ten maxRetries param do tohoto configu, ne?
https://github.com/keboola/db-extractor-mysql/blob/master/tests/functional/run-action-via-ssh-tunnel/source/data/config.json

2022-01-18 10:25 UTC, ondrajodas commented
to nestačí, protože na tom neozkoušíš že to retry zafungvalo... musíš udělat nějaký padající test kde bude vidět že se retry spustilo třeba 10x

2022-01-19 11:07 UTC, AdamVyborny commented
> to nestačí, protože na tom neozkoušíš že to retry zafungvalo... musíš udělat nějaký padající test kde bude vidět že se retry spustilo třeba 10x

hotovo

2022-01-19 11:16 UTC, ondrajodas approved these changes
jo, takhle už to vypadá dobře 👍

2022-01-19 11:42 UTC, merged